### ISSUE TITLE
Multiple layer configurations not working 

### ISSUE THREAD

**Issue by izner32** [nftchef/art-engine#100]
It only generates the one of the two, here is my config 

```
const layerConfigurations = [
  {
    growEditionSizeTo: 1,
    namePrefix: "Male", // Use to add a name to Metadata `name:`
    layersOrder: [
      // { name: "Background" },
      { name: "Offhand" },
      { name: "Base - Male", trait: "Base" },
      // { name: "special" },
      { name: "Clothing - Male", trait: "Clothing" },
      { name: "Mouth" },
      { name: "Ear" },
      { name: "Eyes - Male", trait: "Eyes" },
      // { name: "Face - Male", trait: "Face" },
      { name: "Neckwear - Male", trait: "Neckwear" },
      { name: "Hair - Male", trait: "Hair" },   
      { name: "Headgear" }
    ],
  },
  {
    growEditionSizeTo: 1,
    namePrefix: "Female",
    resetNameIndex: false, // this will start the Lion count at #1 instead of #6
    layersOrder: [
      // { name: "Background" },
      { name: "Offhand" },
      { name: "Base - Female", trait: "Base" },
      // { name: "special" },
      // { name: "Clothing - Female", trait: "Clothing" },
      { name: "Mouth" },
      { name: "Ear" },
      { name: "Eyes - Female", trait: "Eyes" },
      // { name: "Face - Female" },
      { name: "Neckwear - Female" },
      { name: "Hair - Female", trait: "Hair" },   
      { name: "Headgear" }
    ],
  }
];
```

**Comment by izner32** [comment]
It says editions left to create [2, 1] but then proceeded to only create 2 which is the male, it doesn't produce any error to create 1 but then it doesn't create 1 which is the female, if I then generate only the female it works perfectly fine so the problem is when I try to generate both of them together

**Comment by georgekaraan** [comment]
You need to change the growEditionSizeTo in the second layer configuration. 

Right now the code is generating edition 0 and then edition 1 (both Male) but then it can't grow to index 1 as configured in the second layer config because it is already at index 1. So you need to change that to 2. 

If you need to generate 3 males and 5 females, it would look like this:
...
growEditionSizeTo: 2,
    namePrefix: "Male", // Use to add a name to Metadata `name:`
...
growEditionSizeTo: 7,
    namePrefix: "Female", // Use to add a name to Metadata `name:`
...
