### ISSUE TITLE
Duplicates when using bypassDNA

### ISSUE THREAD

**Issue by heeheehy** [nftchef/art-engine#117]
Hi, when I tried using the code to generate a collection with bypassDNA on the background layers, I get some duplicates with no error. However, when I remove the bypassDNA factor, I am able to generate all unique images. 

Not sure what is the issue and need some help.
Thank you.

**Comment by Endrave** [comment]
well i face the same issue, it hv bother me more than a week. I went to deep dive the code a bit n fix that.

in main.js

go find 
`const isDnaUnique = (_DnaList, _dna = [])`
replace the entire function with
`const isDnaUnique = (_DnaList, _dna = []) => {
  const _filteredDNA = filterDNAOptions(_dna);
  return !_DnaList.has(_filteredDNA);
}; `

Also join [my NFT project] ((https://discord.gg/WZpGt24GqC)) , if possible, i will love to your NFT projects too! Cheer!

**Comment by heeheehy** [comment]
hi @Endrave thanks v much! the change worked and resolved the issue.
Also joined ur discord.

Cheers!
