### ISSUE TITLE
Subfolder layering order

### ISSUE THREAD

**Issue by mGonzim** [nftchef/art-engine#12]
Is there a way to dictate in which order a sublayer is chosen. I know files within folders that don't have rarity will be selected alpha but what about subfolders that don't have rarity?

**Comment by nftchef** [comment]
@mGonzim subfolders without rarity are also required, you can think of it as reading "always pick something from this subfolder", and of course, you can have more folders inside and/or weighted images.

if you're referring to the order in which they are stacked, I just released a new feature for controlling `z-index`, much like how CSS works
https://github.com/nftchef/art-engine#Controlling-layer-order-z-index
