### ISSUE TITLE
Nested Layer Order Not Respected

### ISSUE THREAD

**Issue by mojalil** [nftchef/art-engine#141]
Hello All, 

I'd like to start by saying, fantastic work on this art engine. I've been putting together a project and it's mostly going well. However there is one big problem. Nested layer order is not respected, i.e. In  a nested folder layers are not added in the right order.

Here's an example of the nested `folder structure` for cloths

```
Cloths
|--Cloth_01#15
|----1_Base
|------Base_01#10.png
|------Base_02#10.png
|----2_Secondary
|------Secondary_01#10.png
|----3_Tertiary 
|------Tertiary_01#10.png
|----4_LineArt
|------Line_Art#100.png
```

and here is an example of the `config`

```
 {
    growEditionSizeTo: 10,
    layersOrder: [
      { name: "Base Body" },
      { name: "Cloths",
    },
```

For the output I would expect something like below (and that is why i have numbered the folders). Where the line art is the last layer

```
Base_01#10.png
Secondary_01#10.png
Tertiary_01#10.png
Line_Art#100.png
```
Some images will generate with the correct ordering however some will not and i'll get some other layer at the top (not the lineart) like below. 

```
Base_01#10.png
Secondary_01#10.png
Line_Art#100.png

Tertiary_01#10.png
```

Any ideas on why this happens? Going by the docs, all the folders are named correctly.

**Comment by mojalil** [comment]
I've made an adjustment to the sorting function to fix this issue , by sorting the `sort.normal` under `sortLayers` function

```
  stack.normal.sort();

  return sortByZ(stack.front).concat(stack.normal).concat(sortByZ(stack.end));
```

**Comment by nftchef** [comment]
Thank you for the fix @mojalil 👍
