### ISSUE TITLE
bypassDNA option should remove the desired object from the metadata if a couple of changes are made.

### ISSUE THREAD

**Issue by Jharmony** [nftchef/art-engine#161]
After refactoring the hashlips art engine to fix the bypassDNA functionality, and tested it to make sure that the desired metadata is removed. On the hashlips art engine code, as suggested by this issue which was opened on the same matter https://github.com/HashLips/hashlips_art_engine/issues/554, the functionality can be fixed by adding by wrapping this part of the code in an if statement like so:

` if (!_element.layer.bypassDNA) { // Will only allow push if byPassDNA is set to false
  attributesList.push({
    trait_type: _element.layer.name,
    value: selectedElement.name,
  });
 }`

and, 

`bypassDNA: layer.bypassDNA,`

will look into your code and try to submit a pull request if I can figure out the changes that you made to the main.js file.

You can find a working version of Hashlips' art engine in my repo https://github.com/Jharmony/hashlips_art_engine

**Comment by nftchef** [comment]
Fixed in 1ebc82c36dd2b39306fc617e4530d407e9f9cf61
