### ISSUE TITLE
All layers duplicated during image generation.

### ISSUE THREAD

**Issue by PhosphoriaArtist** [nftchef/art-engine#178]
line 354 mainCanvas.drawImage(layerCanvas, 0, 0, format.width, format.height); in the nftchef main.js.
is causing all layers to be drawn twice (this is making all semi-transparent effects broken including blend modes)
I mentioned this in the twitter dev chat but putting it here too.

**Comment by nftchef** [comment]
Thank you for reporting. 
This is now fixed. 🙇
