### ISSUE TITLE
npm run rarity or yarn rarity Not working

### ISSUE THREAD

**Issue by Roskaiu** [nftchef/art-engine#189]
I followed the instructions of https://generator.nftchef.dev/utils/rarity

When I want to execute
![npm run rarity](https://user-images.githubusercontent.com/104800157/169853336-17712322-579a-4dd6-9a2e-2a547d26ee89.png)

That's all I need to get my collection ready.

Thank you

**Comment by jjclay** [comment]
I think I had the same problem.  If you look in the code there is no rarity.js, only rarityData.js (which errors out for me).  I think that I copied rarity.js from the original hashlips repo.  I got errors regarding csv and the NFTChef provided the fix here:  https://github.com/nftchef/art-engine/discussions/146#discussion-4017751

**Comment by Roskaiu** [comment]
Thank you! I'll give that a try

**Comment by buhduhzah** [comment]
this worked for me! it prints a log  `node utils/rarityData.js > rarity.log 2>&1
`

**Comment by Roskaiu** [comment]
I'm getting this error, any ideas? this is all I need to finish. Thank you very much
![a](https://user-images.githubusercontent.com/104800157/172176122-4ab1e910-6d3b-47e7-a29b-793f61ffdc6f.png)
h

**Comment by buhduhzah** [comment]
i forgot that i had run` npm install --save csv-writer` maybe that would help? hopefully someone else knows, i'm more of a copy-paste coder

**Comment by Roskaiu** [comment]
![image](https://user-images.githubusercontent.com/104800157/172272150-c46bc13c-6ebe-4a00-aa30-2f2c00001e59.png)

// Thank you very much for your interest but didn't work. 


npm WARN nft-kitchen-sink-generator@2.0.2 No repository field


// We were able to get all the utilities working. It would only remain the list of rarities to have the project ready. 

I hope to be able to solve this.
if someone can give me a clue where the error may be. 
I will be very grateful.

**Comment by jvelezr** [comment]
Hi what worked for me was to download the rarity.js file from https://github.com/nftchef/art-engine/tree/utils/rarity/utils into the utils folder. 

Then in the package.json file add a line in the "scripts" set with "rarity": "node utils/rarity.js" it will look like this:

```
"scripts": {
    "build": "node index.js",
    "generate": "node index.js",
    "generate:solana": "node index.js && node utils/metaplex.js",
    "generate:cardano": "node index.js && node utils/cardano.js",
    "generate:tezos": "node index.js && node utils/tezos.js",
    "preview": "node utils/createPreviewCollage.js",
    "gif": "node utils/preview_gif.js",
    "update:metadata": "node utils/updateInfo.js",
    "update_info:tezos": "node tezos/updateInfo.js",
    "resize": "node utils/resize.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "rarity": "node utils/rarity.js"
  },
```

Hope it helps!

**Comment by spike-hue** [comment]
The script exists on a different branch called `utils/rarity`. So to use it I did:
1. Checkout the main branch `nested-folder-structure`
2. Generate the images by running `npm run build` 
3. Switch to the branch `utils/rarity`
4. In terminal call `npm run rarity`. Note: You may get an error about `csv-writer` package and need to install it. I did it with `npm i csv-writer`
5. A csv is generated called `_rarity.csv`. Open it with any spreadsheet software

Hope that helps!
