### ISSUE TITLE
Randomly Insert Rare items - Replace Util

### ISSUE THREAD

**Issue by ultraviolet007rainbow** [nftchef/art-engine#196]
### Discussed in https://github.com/nftchef/art-engine/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **ultraviolet007rainbow** May 29, 2022</sup>
Hi, 

Can you please post a sample JSON file of what this should look like exactly, do we not include the DNA as there is no DNA?
Date? Imagehash? etc.?
Does it have to match all the other JSON files as far as all the Metadata because it can't since these 1/1s.
Please clarify.

Thanks :)</div>

**Comment by advra** [comment]
did you ever figure this out?

**Comment by nftchef** [comment]
Updated documentation for the replace util is here: 
https://generator.nftchef.dev/utils/replace-for-rares
