### ISSUE TITLE
const incompatible not working w/ z index

### ISSUE THREAD

**Issue by ghost** [nftchef/art-engine#215]
So I have a incompatibility object

```
const incompatible = {
    ["X"]: ["A", "B", "C", "E", "F"],
    ["Y"]: [ "D" ],
    ["Z"]: ["A", "B", "C"]
}; 
```

and the filenames have been edited to have order for the zIndex. (Replaced the filenames with variable letters)

```
z1,X#2.png
z2,Y#30.png
z3,Z#14.png

z2,A#9.png
z2,B#41.png
z3,C#3.png
z3,D#16.png
z3,E#7.png
z3,F#18.png

```

But the incompatible traits are being generated together and the compiler is ignoring the incompatibility object it seems.

I read this in the documentation:

```
Incompatible and forced combinations run _after_ the z-index modifies 
the layer ordering and can lead to unexpexted output when setting up
 the `key:[values]` pairs. The `key` should always be the item that comes 
first, after the z-index has been applied.
```

Any solutions?

**Comment by advra** [comment]
I am running into the same issues but without Z indexing. I have yet to try Z Indexing but this feature appears to be broken

**Comment by advra** [comment]
I made a post in #254

**Comment by nftchef** [comment]
Issues like this are likely due to typos, e.g. #254 🙇

The config in the original example appears to be OK. If there are more issues, please open a new discussion.
