### ISSUE TITLE
Solana Collection Family not working

### ISSUE THREAD

**Issue by shibakinu** [nftchef/art-engine#223]
I've already changed the infos needed in solana_config.js and after generating in solana metadata, the collectionName and collectionFamily are not showing in those metadata. Can somehow tell me how to fix it? Thank you in advance.

**Comment by nftchef** [comment]
The collection name and collection family were deprecated in the metaplex standard.
https://docs.metaplex.com/programs/token-metadata/token-standard#the-non-fungible-standard

The config option was unnecessarily left in  Solana config and has been removed.
