### ISSUE TITLE
when i run "node index.js"  i got this error SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by goodnonuts** [nftchef/art-engine#226]
when i run "node index.js"  i got this error

if (layer.sublayerOptions?.[sublayer]) {
                            ^
SyntaxError: Unexpected token '.'

**Comment by nftchef** [comment]
Need more info to help debug. 
This may be an issue with the Node version being too low and not supporting Optional Chaining
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
