### ISSUE TITLE
Layers appear very dark

### ISSUE THREAD

**Issue by mistersprinklez** [nftchef/art-engine#235]
pngs with transparency are appearing in the generated images much darker than they actually are.

**Comment by mistersprinklez** [comment]
aside from being darker, they also look contrasty.

**Comment by oneslayer** [comment]
I had the same problem and it was related to duplicate layers. On this url, at commit you have the answer to the problem by modifying the code on main.js
https://github.com/nftchef/art-engine/pull/190

**Comment by nftchef** [comment]
fixed in #190
