### ISSUE TITLE
Regenerate metadata.json from _dna.json. Useful when an error occured while running util scripts.

### ISSUE THREAD

**Issue by rairulyle** [nftchef/art-engine#245]
I just experienced an issue where I broke my metadata.json. I happened to run `node utils/replace.js` and an error occurred but it has successfully modified the JSON, metadata, and images for some.  Now I can't run utils that require `metadata.json` as it is already broken. 

Is there a way to regenerate a `metadata.json` from the `_dna.json` so I don't have to build the whole collection again?

**Comment by nftchef** [comment]
Added this feature 🙇
