### ISSUE TITLE
Cardano.js attribute parsing

### ISSUE THREAD

**Issue by Dripsha** [nftchef/art-engine#249]
Is there a replacement for the following code in the Cardano.js that will give us 721 standards for attributes instead of making them flat objects?

**The output looks like this:**

```
                "attributes":[
                    "Attribute One",
                    "Another attribute",
                    "And another"
```

**But, the standard for separation in the metadata for correct display needs to be outputted as:**

```
                "attributes":[
                {
                    "Attribute One",
                },
                {
                    "Another attribute",
                },
                {
                    "And another"
                }
```
                
**Code in question:**
Start line 60
```

  // convert the array of attributes into a flat object
  // this object is spread into the metadata template
  const restructuredAttributes = {};
  jsonData.attributes.map((attr) => {
    restructuredAttributes[attr.trait_type] = attr.value;
  }, []);

```

**Comment by nftchef** [comment]
Hi! Thank you for the suggestion. 

Were you trying to build for a specific marketplace with its own standard? a link to their documentation would be helpful and I can make a specific util for that output.

Currently, it follows the following standard for metadata (version 1) which unfortunately doesn't describe how to handle attributes, so they fall into the "other" category. https://cips.cardano.org/cips/cip25/

The output should not currently put them in an array but output them as single `key:value` pairs
```
{
  "721": {
    "<policy_id>": {
      "<asset_name>": {
        "name": "Series 2 #0",
        "image": "<ipfs_link>",
        "mediaType": "<mime_type>",
        "description": "This is the description of your NFT project, remember to replace this",
        "files": [
          {
            "name": "<display_name>",
            "mediaType": "<mime_type>",
            "src": "<ipfs_link>"
          }
        ],
        "Background": "swirl",
        "Head": "faceA",
        "Clothes": "shirt two",
        "Shirt Accessories": "GOLDEN NECKLACE",
        "Eyes": "happy",
        "Hair": "bluehair"
      }
    },
    "version": "1.0"
  }
}
```
