### ISSUE TITLE
Hitting duplicate DNA images several times - no error

### ISSUE THREAD

**Issue by ken-vat** [nftchef/art-engine#26]
I am using nftchef with multiple layer sets
Windows 7. Packages, dependencies are upto date
PS C:\Users\...\nftchef\art-engine-nested-folder-structure> node --version 
v16.13.2
PS C:\Users\..\nftchef\art-engine-nested-folder-structure> npm --version
8.1.2
No nested layers - all flat. rarities allocations r there though.
Check out the attachments. spreadsheet has the dups highlighted in pink. Its snipped - full version with 1000 nfts has many dups
Hit this multiple times. Just rebooted the laptop to try again.
If someone hit this and found something, do update.

Config.js
--------
"use strict";

const path = require("path");
const isLocal = typeof process.pkg === "undefined";
const basePath = isLocal ? process.cwd() : path.dirname(process.execPath);
const { MODE } = require(path.join(basePath, "src/blendMode.js"));

const buildDir = path.join(basePath, "/build");
const layersDir = path.join(basePath, "/layers");

const description =
  "BTTTTMTTTT";
const baseUri = "ipfs://UPDATE";

const outputJPEG = false; // if false, the generator outputs png's
/**
[duplicate-dna-snip.xlsx](https://github.com/nftchef/art-engine/files/8021416/duplicate-dna-snip.xlsx)
![layers-pic-dna-err](https://user-images.githubusercontent.com/40846144/152933368-370b49ec-f0b8-4414-8600-2f825c58540d.png)

 * Set your tokenID index start number.
 * ⚠️ Be sure it matches your smart contract!
 */
const startIndex = 0;

// if you use an empty/transparent file, set the name here.
const emptyLayerName = "NONE";

//IF you need a provenance hash, turn this on
const hashImages = false;

const layerConfigurations = [
  // Rangers group layers
  {
    growEditionSizeTo: 300,
   
    layersOrder: [
      
      { 
        name: "BeeClan",   //dummylayer
        options: {
          bypassDNA: true,
        }
      },      
      { name: "Island" },

      { name: "BeeWings" },

      //this is dummy layer
      { name: "Holstered" },

      { name: "BeeCore"  },
      { name: "BeeFamilyStyle" },  // This is body pattern
      { 
        name: "BeeFamily", 
        options: {
          bypassDNA: true,
        }
      },   

      { name: "SpectrumAntennae" },
      { name: "VisorGear"  },
      { name: "Weapons" },
      { name: "RightArmOver" },
      
    ],
  },
  // Brawnies LayerGroup2
  {
    growEditionSizeTo: 450,
    layersOrder: [
   
      { 
        name: "BeeClan",   //dummylayer
        options: {
          bypassDNA: true,
        }
      },      
      { name: "Island" },

      { name: "BeeWings" },
      { name: "Holstered" },
      { name: "BeeCore"  },
      { name: "BeeFamilyStyle" },  // This is body pattern
      { 
        name: "BeeFamily", 
        options: {
          bypassDNA: true,
        }
      },

      { name: "ManaVacCannister" },
      // remove this in metadata
      { name: "BrawnyShield" },
      { name: "SpectrumAntennae" },
      { name: "VisorGear"  },

    ],
  },

  // Diviners LayerGroup3
  {
    growEditionSizeTo: 500,
    layersOrder: [

      { 
        name: "BeeClan",   //dummylayer
        options: {
          bypassDNA: true,
        }
      },    
      { name: "Island" },

      { name: "BeeWings" },
      { name: "Holstered" },  
      { name: "BeeCore"  },
    
      { name: "BeeFamilyStyle" },  // This is body pattern
      { 
        name: "BeeFamily", 
        options: {
          bypassDNA: true,
        }
      },

      { name: "ManaExtractor"  },
      { 
        name: "SpectrumXSAntennae", trait: "SpectrumAntennae" 
      },
      { name: "VisorGear"  },
      { name: "Tools" },
      { name: "RightArmOver" },
    ],
  },
];

/**
 * Incompatible items can be added to this object by a files cleanName
 * This works in layer order, meaning, you need to define the layer that comes
 * first as the Key, and the incompatible items that _may_ come after.
 * The current version requires all layers to have unique names, or you may
 * accidentally set incompatibilities for the _wrong_ item.
 */
const incompatible = {
  //   Red: ["Dark Long"],
  //   // directory incompatible with directory example
  //   White: ["rare-Pink-Pompadour"],
};

/**
 * Require combinations of files when constructing DNA, this bypasses the
 * randomization and weights.
 *
 * The layer order matters here, the key (left side) is an item within
 * the layer that comes first in the stack.
 * the items in the array are "required" items that should be pulled from folders
 * further in the stack
 */

// Clan 3
const forcedCombinations = {

  ChiefDiamondStonerWing: ["ChiefDiamondStoner", "DegenStoners"],
  AmethystStonerWing: ["AmethystStoner", "DegenStoners"],
  GoldStonerWing: ["GoldStoner", "DegenStoners"],
  RubyStonerWing: ["RubyStoner", "DegenStoners"],
  SaphireStonerWing: ["SaphireStoner", "DegenStoners"],
  EmeraldStonerWing: ["EmeraldStoner", "DegenStoners"],

  ChiefSpookySpiritWing: ["ChiefSpookySpirit", "SpookySpirits"],
  EarthSpiritWing: ["EarthSpirit", "SpookySpirits"],
  WindSpiritWing: ["WindSpirit", "SpookySpirits"],
  WaterSpiritWing: ["WaterSpirit", "SpookySpirits"],
  FireSpiritWing: ["FireSpirit", "SpookySpirits"],
  EtherSpiritWing: ["EtherSpirit", "SpookySpirits"],

  ChiefFlamingFuryWing: ["ChiefFlamingFury", "FlamingFury"],
  NightfallFuryWing: ["NightfallFury", "FlamingFury"],
  GoldFuryWing: ["GoldFury", "FlamingFury"],
  SmokyFuryWing: ["SmokyFury", "FlamingFury"],
  PurpleFuryWing: ["PurpleFury", "FlamingFury"],
  ForestFuryWing: ["ForestFury", "FlamingFury"],

};  

/* Clan 2
const forcedCombinations = {

  CocktailBoozyWing: ["CocktailBoozy", "BoozyBand"],
  VinoBoozyWing: ["VinoBoozy", "BoozyBand"],
  BeerBoozyWing: ["BeerBoozy", "BoozyBand"],
  WhiskeyBoozyWing: ["WhiskeyBoozy", "BoozyBand"],
  SakeBoozyWing: ["SakeBoozy", "BoozyBand"],
  VodkaBoozyWing: ["VodkaBoozy", "BoozyBand"],
  TequilaBoozyWing: ["TequilaBoozy", "BoozyBand"],

  RainbowFizzWing: ["RainbowFizz", "FruityFizzFam"],
  BlueberryFizzWing: ["BlueberryFizz", "FruityFizzFam"],
  CherryFizzWing: ["CherryFizz", "FruityFizzFam"],
  PineappleFizzWing: ["PineappleFizz", "FruityFizzFam"],
  FigFizzWing: ["FigFizz", "FruityFizzFam"],
  KiwiFizzWing: ["KiwiFizz", "FruityFizzFam"],
  GrapeFizzWing: ["GrapeFizz", "FruityFizzFam"],

  BouquetOFlowersWing: [ "BouquetOFlowers", "FloraBrigade"],
  PassionFlowerWing: [ "PassionFlower", "FloraBrigade"],
  MarigoldFlowerWing: [ "MarigoldFlower", "FloraBrigade"],
  LavenderFlowerWing: [ "LavenderFlower", "FloraBrigade"],
  DahliaFlowerWing: [ "DahliaFlower", "FloraBrigade"],
  RedRoseFlowerWing: [ "RedRoseFlower", "FloraBrigade"],
  IrisFlowerWing: [ "IrisFlower", "FloraBrigade"],
  
};
*/

const shuffleLayerConfigurations = false;

/**
 * In the event that a filename cannot be the trait value name, for example when
 * multiple items should have the same value, specify
 * clean-filename: trait-value override pairs. Wrap filenames with spaces in quotes.
 */

const traitValueOverrides = {
//  Helmet: "Space Helmet",
//  "gold chain": "GOLDEN NECKLACE",
};

const debugLogs = false;

const format = {
  width: 1024,
  height: 1024,
};

const background = {
  generate: false,
  brightness: "80%",
};

const extraMetadata = {};

const extraAttributes = () => [
  // Optionally, if you need to overwrite one of your layers attributes.
  // You can include the same name as the layer, here, and it will overwrite
  //
  // {
  // trait_type: "Bottom lid",
  //   value: ` Bottom lid # ${Math.random() * 100}`,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Aqua Power",
  //   value: Math.random() * 100,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Health",
  //   value: Math.random() * 100,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Mana",
  //   value: Math.floor(Math.random() * 100),
  // },
];

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

/**
 * Set to true to always use the root folder as trait_tybe
 * Set to false to use weighted parent folders as trait_type
 * Default is true.
 */
const useRootTraitType = true;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.width / format.height,
  imageName: "preview.png",
};

module.exports = {
  background,
  baseUri,
  buildDir,
  debugLogs,
  description,
  emptyLayerName,
  extraAttributes,
  extraMetadata,
  forcedCombinations,
  format,
  hashImages,
  incompatible,
  layerConfigurations,
  layersDir,
  outputJPEG,
  preview,
  rarityDelimiter,
  shuffleLayerConfigurations,
  startIndex,
  traitValueOverrides,
  uniqueDnaTorrance,
  useRootTraitType,
};

**Comment by nftchef** [comment]
hi @ken-vat 

Unfortunately I can't see the highlights in the excel file, can you share a screenshot of a few of the ones that are duplicated and if you have narrowed it down to a few traits, that would be very helpful
