### ISSUE TITLE
typo in blendMode.js 

### ISSUE THREAD

**Issue by dawnharmony** [nftchef/art-engine#40]
in BlendMode.js 

it is stated as:

sourceOut: "source-out",
sourceAtop: "source-out",

so whenever someone tries to use sourceAtop feature, it results in sourceOut instead. It was a little confusing till i figured out where the problem was. Please update it to: 

sourceAtop: "source-atop", so others won't have the same problem. 

Thanks a lot for your work, this is a great repo!

**Comment by nftchef** [comment]
Thank you!
