### ISSUE TITLE
Improvement request/help

### ISSUE THREAD

**Issue by zoultrex** [nftchef/art-engine#43]
I need to make a specific file to be incompatible with an entire folder
For example I'm creating an avatar that has folder with clothes, then another folder with necklaces
I need to add to incompatible object a single piece of clothing by its filename, then say that it wont be compatible with any file on necklace folder
lets say I have inside Clothes folder, the files clothes_01, clothes_02, clothes_03 and so on...
This is how the incompatible object would be represented

`const incompatible = {
    Clothes_03: ["Necklace"],
};`

Could you suggest the right approach to achieve this? I can totally do that just on my side of the code if you don't plan to support this

Thanks!

**Comment by zoultrex** [comment]
I did something that solved the problem for me, but I did not test the entire tool to know if this could cause more issues, so far it worked without showing any bugs:

```
const compatibleLayers = layer.elements.filter(
    (layer) => !incompatibleDNA.includes(layer.name) && !incompatibleDNA.includes(layer.trait)
  );
```

I'll create a PR so the tool can have support for this

**Comment by sturench** [comment]
I just worked on understanding nested folders (and z-index) for a day or so.  In my opinion, there are very few things that can't be solved using those tools.  I was able to remove all of my "incompatible layer" configs once I grasped the beauty and power of nested/z-index!
Here is the resulting documentation from working with @nftchef to unpack the features: https://generator.nftchef.dev/readme/z-index-layer-order

He is still working on cleaning up all of the documentation, but this might help.

**Comment by zoultrex** [comment]
> I just worked on understanding nested folders (and z-index) for a day or so. In my opinion, there are very few things that can't be solved using those tools. I was able to remove all of my "incompatible layer" configs once I grasped the beauty and power of nested/z-index! Here is the resulting documentation from working with @nftchef to unpack the features: https://generator.nftchef.dev/readme/z-index-layer-order
> 
> He is still working on cleaning up all of the documentation, but this might help.

Thanks for the feedback
I would love to be able to remove my incompatibles, its becoming messy, even after changing that piece of code mentioned above

I have to confess that I could not grasp the idea of the nested folders for my case, maybe you can help me figure out if this would also work for me?

Here is my scenario

I'm building a character with these layers: ( layers are in correct order here, I use no sublayers)
```
Background
Face
Clothes
Eye
Head
Necklace
Hands
Mouth
```

I'll need to generate for example:
6 super rare items
20 rare items
100 common items

The 6 super rare items should be made of 4 unique necklaces and 2 unique hands. Only 1 of each should be used, meaning that I'll have super_rare_img1 generated with necklace1, super_rare_img2 generated with necklace2... up to necklace 4, and same thing for hand 1 and so on...
None of those 6 super rare items can repeat at any other time for the entire collection
Also there are exclusion rules where those 4 necklaces cannot be added to an image with specific Clothes items (for this I added each Clothes_item_x, Clothes_item_x+1 etc to incompatible list matching the 4 necklaces

This is the overall gist of what I need... I need specific items to be used a certain number of times only, in super rare case each item should be used only once to generate an image. In the case of rare items, they can be used 2 or 3 times in different images and many times they have a different exclusion rule...

I'm starting to think that I better first separate all images for rare and super rare into folders where: if I want an item to be used only once, id create a folder for example Necklace_super_rare_1 and place in there only that one image. I'd repeat this for Necklace 2,3 and 4, each into a single folder. After that then generate first the super rare collection matching those folder names where my layerConfigurations would grow by 1 each time I select one of those specific super rare items...

I actually did test that case for those 6 super rare images and it did come out as I wanted. I'm thinking about doing the same for rare and so on.
I have greatly reduced the amount of examples here just to illustrate, I have 5 tiers (super rare, rare, special etc...) and a varied number of images that can be generated and items to be used for specific amount of times also some common exclusion rules and some specific exclusion rules depending on the tier

Thoughts?

**Comment by sturench** [comment]
I think this can be achieved using a combination of nested folders and
adding multiple layer configurations. One of those configurations would
simple be extended by 1 and contain the super rare item in the nested
folders to be combined with others.

The other option is to manually create the super rare and use the utility
to replace and slip in your uniques...this might be best given what you
said. This would leave nothing to chance on the super rare.

**Comment by zoultrex** [comment]
> I think this can be achieved using a combination of nested folders and adding multiple layer configurations. One of those configurations would simple be extended by 1 and contain the super rare item in the nested folders to be combined with others. The other option is to manually create the super rare and use the utility to replace and slip in your uniques...this might be best given what you said. This would leave nothing to chance on the super rare.

Yea thats pretty much what I had in mind too, thanks again for the feedback
