### ISSUE TITLE
Cannot run any utils at all, weird, plz help :)

### ISSUE THREAD

**Issue by ultraviolet007rainbow** [nftchef/art-engine#60]
### Discussed in https://github.com/nftchef/art-engine/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **ultraviolet007rainbow** February 23, 2022</sup>
Hi,

For some reason I try running any util and none of them are found by name.

npm run rarityData

npm run provenance

etc.

I generated all my art, JSONs and the main JSON, all in the correct default folders.

So why does it keep failing?

Any ideas would be appreciated.

Thanks.

</div>

**Comment by nftchef** [comment]
Hi, Not all of the scripts have a script alias for npm or yarn 
(check package.json for available scripts)

I may add them soon for convenience. for now, all scripts can be run directly with node
```
// node utils/<scriptName>.js
