### ISSUE TITLE
Issue with shuffleLayerConfigurations

### ISSUE THREAD

**Issue by nftchef** [nftchef/art-engine#66]
### Discussed in https://github.com/nftchef/art-engine/discussions/64

<div type='discussions-op-text'>

<sup>Originally posted by **AC1AN** February 24, 2022</sup>
Hi, I noticed that when I turn on theshuffleLayerConfigurations the generator always skip a number, for example if I ask for 5 images I'll have a result like 1 2 4 5 6 , with a gape in it
In this example I asked for 10 and the number 2 is missing I have instead number 11 
![shuffleissue](https://user-images.githubusercontent.com/100198428/155518525-8c4e2ff4-f448-40f6-970f-b20f7256b56c.png)
.

Thank you </div>

**Comment by shingsoso** [comment]
I faced the same problem. Have you figured out what caused that ?

**Comment by shingsoso** [comment]
Check this out , a quick fix
https://github.com/nftchef/art-engine/issues/70#issuecomment-1053605090

**Comment by nftchef** [comment]
TY @shingsoso! I will hopefully have it fixed this week.
