### ISSUE TITLE
One set of image & json will be missing 

### ISSUE THREAD

**Issue by shingsoso** [nftchef/art-engine#70]
There is always one set of image and json missing when we have multiple layer configuration and shuffleLayerConfiguration.

For example , with the setting below : 

```
const layerConfigurations = [
  {
    growEditionSizeTo: 2,
    layersOrder: [ ...]
   },
  {
    growEditionSizeTo: 5,
    layersOrder: [ ...]
   }
];
```

`const shuffleLayerConfigurations = true;`

The 2.png & 2.json will always be missing in the build.

**Comment by shingsoso** [comment]
I have made a quick fix on the issue above , in the `/src/main.js`
The quick fix is to change the line in while loop to this : 
`editionCount <= layerConfigurations[layerConfigIndex].growEditionSizeTo + 1`


```
const startCreating = async (storedDNA) => {
  if (storedDNA) {
    console.log(`using stored dna of ${storedDNA.size}`);
    dnaList = storedDNA;
  }
...
    while (
      editionCount <= layerConfigurations[layerConfigIndex].growEditionSizeTo + 1
    ) {
      let newDna = createDna(layers);
   ...
};
```

**Comment by nftchef** [comment]
No longer an issue
