### ISSUE TITLE
Issue once running script: Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by r1fel** [nftchef/art-engine#71]
Hello everyone and hello NFT Chef,

I just tried to build my collection but im running into a problem:

(node:19510) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

Clearing canvas
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /.../node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /.../node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

My operating System is IOS 10.13, but i cannot really upgrade to Catalina. 
I've seen that this problem came up once at the issues of the HAE, and supposedly it was due to some dependencies, I wonder if you could also have a look at this in your fork?
If anybody has other ideas how to solve this issue I would be glad to hear them.

Here the link to the older thread referring to the same issue:
https://github.com/HashLips/hashlips_art_engine/issues/1
 
Thank you!

**Comment by nftchef** [comment]
This is an issue with the underlying build for canvas.
Have you tried the following?
1. Delete node_modules folder `rm -rf node_modules/`
2. remove Canvas from `package.json` (delete the line in dependencies)
3. `npm i` or `yarn` to install dependencies
4. install canvas `npm i --save canvas` or `yarn add canvas`


This _should_ grab the correct build of canvas for your machine. if you get a "no precompiled binary for ____ your  OS and node version" error, you may need to reference the Canvas repo for available builds and change your Node.js versions

These errors are tricky!

**Comment by nftchef** [comment]
have you had any luck solving this? It seems like you are having the same issue as here,
https://github.com/Automattic/node-canvas/issues/1626

**Comment by r1fel** [comment]
Thanks for finding the thread!
I might try the next days to reinstall the specific versions. If i find out something i'll let you know.
For now I just did it from my windows laptop and it worked just fine. 
Thanks for the great fork : )
