### ISSUE TITLE
Question: Why do images generate 1 extra

### ISSUE THREAD

**Issue by Majakhtar** [nftchef/art-engine#76]
Hello, Thank you for this generator! 

Just a question not sure if this is an issue.
I want to generate 20 images, I get 21 images instead. I changed the start index to 1, as I assumed this maybe because the images started with a 0 but the generator is still producing an extra image. 

Thank you =)

**Comment by nftchef** [comment]
Hi, are you using `shuffleLayerConfigurations`? there's a known issue #70 related to that, 

if not, what configuration are you using? can you share your config?

**Comment by Majakhtar** [comment]
Hi, I also had the same issue as #70 and added the new line in main.js

I am sorry, I`m new to Github so not sure how to share and which portion you would like to see? 

Can I private message message you via a screenshot?

Thank you

**Comment by Majakhtar** [comment]
![LayerCapture](https://user-images.githubusercontent.com/100649632/156174770-0a9c6714-2aa7-48dc-b102-84123a2804fa.PNG)
