### ISSUE TITLE
RarityData.js fails Cannot read properties of undefined

### ISSUE THREAD

**Issue by nftchef** [nftchef/art-engine#8]
known Issue reading traits when anything has been modified or added.

```
rarityDataTraits.elements.forEach((rarityDataTrait) => { ^

TypeError: Cannot read properties of undefined (reading 'elements')
```

I am currently in the process of rewriting the rarity data util with an expected release by the first week of Feb 2022 🤞

**Comment by nftchef** [comment]
WIP rewrite of rarity utility is in this branch for those who need it asap. 

https://github.com/nftchef/art-engine/tree/utils/rarity

documentation can be found on the WIP new gitbook https://0n10ndevision.gitbook.io/nftchef-art-engine/utils/rarity

**Comment by buhduhzah** [comment]
`npm run rarity ` didn't work, but i used `node utils/rarityData.js > rarity.log 2>&1` and it printed a rarity.log 👍
