### ISSUE TITLE
I can't generate images with layers without weight (Nested folders don't work)

### ISSUE THREAD

**Issue by alebradazan** [nftchef/art-engine#83]
If I have one .png without weight (example: Body.png) I receive this error: 

TypeError: Cannot read properties of undefined (reading 'split')
    at cleanDna (C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\src\main.js:54:25)
    at C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\src\main.js:151:22
    at Array.find (<anonymous>)
    at C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\src\main.js:150:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\src\main.js:149:35)
    at startCreating (C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\src\main.js:248:23)
    at C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\index.js:13:3
    at Object.<anonymous> (C:\Users\Abi\OneDrive\Desktop\MfersKittens\artengine\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    
    Also I have the exact problem If I have one file with a "space" in the name, example: Black Shirt.png (I receive the same error)

**Comment by alebradazan** [comment]
Hi! yesterday I found your fork, I:

1) Download directly the  v1.0.6_update: https://github.com/nftchef/art-engine/releases/tag/v1.0.6_update
2) Extracted, open the folder on VSC, opened the terminal and ran: "npm i"
3) Did a test build, worked fine.
4) I deleted the example layers and put my own, that error came out.
5) Changed every filename to delete spaces and add #
6) Worked fine
7) Tried to delete # in some layers filename and keep it without spaces (didn't work)
8) Tried to add the spaces in some filename and keep it with # (didn't work)
9) Tried nested folders with # and without spaces in every filename (didn't work)

**Comment by alebradazan** [comment]
I will try to do everything again and let you know

**Comment by alebradazan** [comment]
New disk, new folder, new installation (the path to the folder doesn't have space or -).

When I run "npm i" I receive:

> PS E:\ArtEngine\newartengine> npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
added 65 packages, and audited 66 packages in 19s
5 packages are looking for funding
  run `npm fund` for details
2 high severity vulnerabilities
To address all issues, run:
  npm audit fix
Run `npm audit` for details.

If I run "npm audit" I receive:

> Run `npm audit` for details.
PS E:\ArtEngine\newartengine> npm audit
npm audit report
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch
simple-get  3.0.0 - 3.1.0
Severity: high
Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv    
fix available via `npm audit fix`
node_modules/simple-get
2 high severity vulnerabilities
To address all issues, run:
  npm audit fix

Should I run "npm audit fix"? Sorry, I'm new on this

**Comment by alebradazan** [comment]
Ok, I didn't run "npm audit fix", tried generating images:
1) Now it works with spaces on the filenames.
2) It works with filenames without # weight, however, the files without weight are simply ignored on the generation (and not forced)
3) Nested folders still don't work

**Comment by alebradazan** [comment]
> Hi, when did you download the repo? the line numbers in the error do not seem to match the latest release. Then engine should be able to handle images with spaces and without weights (required files) just fine. I suspect there is something else going on here, I would need a bit more info to figure it out.

My only question is, now that I download the correct version, it stills have the problem of

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch

simple-get  3.0.0 - 3.1.0
Severity: high
Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv
fix available via `npm audit fix`
node_modules/simple-get

2 high severity vulnerabilities


should I npm audit fix this or not?

**Comment by nftchef** [comment]
if those are warnings and not _errors_ you should be ok to fix them.
