### ISSUE TITLE
One image missing and one additional at the end?

### ISSUE THREAD

**Issue by ultraviolet007rainbow** [nftchef/art-engine#86]
### Discussed in https://github.com/nftchef/art-engine/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **ultraviolet007rainbow** March  1, 2022</sup>
Hi,

I just generated 10K again starting with 1, and ended up with 10,001 as the final image.
I went through and found out that there was a missing image at 7630.
So I edited the JSON of 10,001 to become 7630 instead as it should have been and made sure all the filenames were changed as well (JSON and Image). Will this affect the _dna.json in any way? I did identify the correct DNA line in the _dna.json that corresponds to image 10,0001 which is now image 7630. But I do not see anything in the _dna.json that would directly link it other than the traits to a specific filename (JSON or image). So is there a way to regenerate the _dna.json from the JSON files now that I have fixed the problem manually?

In addition, I found an oddity looking at the _dna.json where one of my background images I used has a numerical filename, none of the other layer files have numerical names other than this one. So in the _dna.json each one of those that has that specific background layer has 0.0 at the head of the line, which clearly is wrong. So for some reason the 0.0 was set because of the numerical layer name, is my assumption. 

Is there a good way to fix this problem?

My only idea is to rename the layer to something else in every JSON file as well as the actual layer name of that specific background PNG.

And also replace all instances in the _dna.json file of that numerical layer name.

Once again will this break anything, can I regenerate the _dna.json from the altered JSON files?

Thank you for your great improvements and enhancements to the original code.

Regards.</div>

**Comment by aysesancili** [comment]
i have same problem.

**Comment by nftchef** [comment]
fixed in #163
