### ISSUE TITLE
Force Combination Error

### ISSUE THREAD

**Issue by VeriumETH** [nftchef/art-engine#92]
Hello, 

Every time the engine attempts to create a forced combination that includes a nested layer after a previous layer it errors back like when you miss type a clean name. If I list it first and then any layers after it will work perfectly fine.

How can I fix this issue?

**Comment by nftchef** [comment]
Hi, Can you share a bit more details? 
How are your layersOrders configured, and the files/folders, and please share your forcedCombinations object.

**Comment by VeriumNFT** [comment]
So I have 11 layers shown below:

      { name: "z-3,Background" },
      { name: "Effect" },
      { name: "Hand" },
      { name: "Race" },
      { name: "Face" },
      { name: "Eyes" },
      { name: "Clothing" },
      { name: "Mouth" },
      { name: "Hair" },
      { name: "Ear" },
      { name: "Hat" },

There are 4 nested folders inside clothing that have two parts, one with a z-2 behind all properties but on top of the background and another part with a z1 on top of everything. Let's just call them Clothing 1-4. When I try to list the nest folder clean name after any layer name that comes before Clothing it errors out with the same error whenever the name is misspelled. For example, if I used a specific Eye trait to force combine with Clothing 1 **"Blue Eyes": ["Clothing 1"],** 

I currently have several incompatibilities using clean names only and here is a run down below in the order it is written:

All Background properties NOT COMPATIBLE WITH specific Race, Clothing, & Hair properties.

Single Effect property NOT COMPATIBLE WITH specific Hand properties.

A few Hand properties NOT COMPATIBLE WITH specific Hair property.

Several Race properties NOT COMPATBILE WITH all Face, all Eyes, some Clothing, all Mouth, all Hair properties.

A few Clothing properties NOT COMPATIBLE WITH most Hair properties.

All Hair properties NOT COMPATIBLE WITH some Hat properties.

**Comment by thepeanutgalleryandco** [comment]
@VeriumNFT you can also check out the editions for incompatibilities, dependencies and maximum repeatability that i have added if you are still having issues.

**Comment by VeriumNFT** [comment]
@thepeanutgalleryandco I was able to solve my issue by manually fixing the images with compatabilityil issues. There where only 4 of them .

I definitely need to checkout the latest video which explains nesting more. I do like the idea of a  maximum repeatability function. Would that be included in your fork of this repo or is it in a pull request?

**Comment by thepeanutgalleryandco** [comment]
@VeriumNFT it is in my own repo, unfortunately.

**Comment by nftchef** [comment]
Oh there's a video? A link would be great to add if someone has made a video.

**Comment by VeriumNFT** [comment]
Apologies, I don't believe there is a video. I posted one and removed it because it didn't contain the information I thought it would.
